---
settings:
  name: Astra Control Center
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  versions:
    - version-number: "22.04"
      url: /astra-control-center-2204
    - version-number: "22.08"
      url: /astra-control-center-2208
    - version-number: "21.12"
      url: /astra-control-center-2112
    - version-number: "21.08"
      url: /astra-control-center-2108
sidebar:
  entries:
    - title: Astra Control Center 22.04 docs
      url: /index.html
    - section: release-notes
    - section: concepts
    - section: get-started
    - section: use
    - section: rest-api
    - section: solutions
    - section: support
    - title: Earlier versions
      url: /acc-earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Astra
  repo: astra-family

